# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
#
nuxeo:
  mongodb:
    dbname: nuxeo
  elasticsearch:
    clusterName: elasticsearch
    indexName: nuxeo
  custom_params: |-
    ## add any other params that go into nuxeo.conf
replicaCount: 1
service:
  name: nuxeo-notification-stream
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
#resources:
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 400m
#    memory: 512Mi
probePath: /nuxeo/runningstatus
livenessProbe:
  initialDelaySeconds: 100
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
  timeoutSeconds: 10
readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 100
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 10
terminationGracePeriodSeconds: 10
mongodb:
  usePassword: false
elasticsearch:
  appVersion: "6.2"
  client:
    replicas: 1
  master:
    replicas: 2
  data:
    replicas: 1