apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/glefevre/nuxeo-notification-stream:{{.VERSION}}"
  artifacts:
  - imageName: nuxeo-notification-stream-with-jx
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/glefevre/nuxeo-notification-stream:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: nuxeo-notification-stream
        chartPath: charts/nuxeo-notification-stream
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/glefevre/nuxeo-notification-stream"
          image.tag: "{{.DIGEST_HEX}}"
